version: '3.9'
services:
  todays-menu-api:
    build: .
    ports:
      - 8080:8080
    environment:
      DB_USERNAME: root
      DB_PASSWORD: example
      DB_URL: mongo:27017
  mongo:
    image: mongo:5
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
